# Generated by Django 6.0.4 on 2026-05-18 00:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       migrations.AddField(
    model_name='product',
    name='user',
    field=models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=django.db.models.deletion.CASCADE
    ),
    preserve_default=False,
),
 ]

