# Generated by Django 6.0.4 on 2026-05-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_quantity',
            field=models.IntegerField(default=5),
        ),
    ]
